import {createState,appendLog,applyBackendState} from "./state.mjs";
const {invoke}=window.__TAURI__.core,{listen}=window.__TAURI__.event;
let state=createState(); const $=s=>document.querySelector(s);
const labels={overview:"Visão geral",operation:"Operação",settings:"Configurações",history:"Histórico",console:"Console"};
async function request(command,payload={}){try{return await invoke("backend_request",{command,payload})}catch(e){toast(String(e),true);throw e}}
function toast(msg,err=false){const el=$("#toast");el.textContent=msg;el.style.borderColor=err?"var(--danger)":"var(--ok)";el.className="show";setTimeout(()=>el.className="",3500)}
function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
function render(){const s=state;$("#status").textContent=!s.connected?"Backend desconectado":s.botRunning?"● Bot rodando":s.ready?"Pronto":"Falta configurar";const t=$("#toggle");t.textContent=s.botRunning?"Parar bot":"Iniciar bot";t.className=s.botRunning?"primary stop":"primary";t.disabled=!s.connected||s.actionRunning||(!s.botRunning&&!s.ready);$("#title").textContent=labels[s.page];document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===s.page));const c=$("#content");
if(s.page==="overview")c.innerHTML=`<div class="grid"><div class="card"><p>Status</p><div class="metric">${s.botRunning?"Ativo":"Parado"}</div></div><div class="card"><p>Histórico carregado</p><div class="metric">${s.history.length}</div></div><div class="card"><p>Dados</p><small>${esc(s.dataDir||"—")}</small></div></div><div class="card"><h2>Próximos passos</h2><p>${s.ready?"Configuração principal concluída.":"Abra Configurações e preencha Telegram e afiliados."}</p></div>`;
if(s.page==="operation")c.innerHTML=`<div class="card"><h2>Ações</h2><div class="actions"><button data-action="cycle">Executar ciclo agora</button><button data-action="ml">Testar Mercado Livre</button><button data-action="shopee">Testar Shopee</button><button data-action="amazon">Testar Amazon</button><button data-action="login">Login Mercado Livre</button><button data-action="browser">Instalar navegador</button></div></div><div class="card"><p>${s.actionRunning?"Operação em andamento…":"Nenhuma operação em andamento."}</p></div>`;
if(s.page==="console")c.innerHTML=`<div class="card"><div class="actions"><button data-action="clear">Limpar visualização</button><button data-action="export">Exportar diagnóstico</button></div></div><div class="log" role="log">${s.logs.map(l=>`[${esc(l.timestamp||"")}] ${esc(l.level||"INFO")} ${esc(l.source||"")} — ${esc(l.message||"")}`).join("\n")||"Aguardando logs…"}</div>`;
if(s.page==="history")c.innerHTML=`<div class="card"><table><thead><tr><th>Plataforma</th><th>Título</th><th>Preço</th><th>Data</th></tr></thead><tbody>${s.history.map(i=>`<tr><td>${esc(i.plataforma)}</td><td>${esc(i.titulo)}</td><td>${i.preco==null?"—":`R$ ${Number(i.preco).toFixed(2)}`}</td><td>${esc(i.postada_em)}</td></tr>`).join("")}</tbody></table></div>`;
if(s.page==="settings"){const e=s.settings?.env||{},p=s.settings?.preferences||{};c.innerHTML=`<form class="card" id="settings-form"><h2>Telegram</h2>${field("TELEGRAM_BOT_TOKEN","Token do bot",e,true)}${field("TELEGRAM_OWNER_ID","Seu user ID",e)}${field("TELEGRAM_CHAT_ID","ID do canal",e)}<h2>Afiliados</h2>${field("ML_ETIQUETA","Etiqueta Mercado Livre",e)}${field("AMAZON_TAG","Tag Amazon",e)}${field("SHOPEE_APP_ID","App ID Shopee",e)}${field("SHOPEE_APP_SECRET","Secret Shopee",e,true)}<h2>Aplicativo</h2><label><input id="start-windows" type="checkbox" ${p.startWithWindows?"checked":""}> Iniciar com o Windows</label><br><label><input name="autoStartBot" type="checkbox" ${p.autoStartBot?"checked":""}> Ligar o bot automaticamente</label><div class="actions" style="margin-top:16px"><button class="primary" type="submit">Salvar configurações</button><button type="button" data-action="import">Importar instalação atual</button></div></form>`}bind();}
function field(k,label,e,secret=false){const set=e[k]==="__CONFIGURED__";return `<label class="field">${label}${set?" ✓":""}<input name="${k}" type="${secret?"password":"text"}" value="${set?"":esc(e[k])}" placeholder="${set?"Preenchido — deixe vazio para manter":""}"></label>`}
function bind(){document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>action(b.dataset.action));const f=$("#settings-form");if(f)f.onsubmit=saveSettings}
async function action(a){if(a==="clear"){state={...state,logs:[]};render();return}if(a==="export"){await navigator.clipboard.writeText(state.logs.map(l=>`${l.timestamp} ${l.level} ${l.source}: ${l.message}`).join("\n"));toast("Diagnóstico copiado.");return}if(a==="import"){const source=await invoke("choose_legacy_folder");if(source&&confirm(`Importar uma cópia dos dados de ${source}?`)){const r=await request("import_legacy_data",{source});toast(`${r.offers} ofertas importadas.`);state.settings=await request("get_settings");}return}if(a==="cycle"&&!confirm("Este ciclo pode publicar ofertas no canal. Continuar?"))return;const map={cycle:["run_cycle",{confirmed:true}],ml:["test_source",{source:"ml"}],shopee:["test_source",{source:"shopee"}],amazon:["test_source",{source:"amazon"}],login:["start_ml_login",{}],browser:["install_browser",{}]};await request(...map[a]);toast("Operação concluída.")}
async function saveSettings(ev){ev.preventDefault();const data=new FormData(ev.target),env={};for(const [k,v] of data)if(k!=="autoStartBot")env[k]=v;const preferences={startWithWindows:$("#start-windows").checked,autoStartBot:data.has("autoStartBot")};await invoke("set_autostart",{enabled:preferences.startWithWindows});await request("save_settings",{env,preferences});state.settings=await request("get_settings");toast("Configuração salva.");render()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{state={...state,page:b.dataset.page};render()});$("#toggle").onclick=async()=>{await request(state.botRunning?"stop_bot":"start_bot");};
await listen("backend://log",e=>{state=appendLog(state,e.payload);if(state.page==="console")render()});await listen("backend://state",e=>{state=applyBackendState(state,e.payload.state||e.payload);render()});
try{state=applyBackendState(state,await request("get_status"));state.settings=await request("get_settings");state.history=(await request("get_history",{limit:100,offset:0})).items}catch{}render();
